/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Kurator */

#ifndef _Included_Kurator
#define _Included_Kurator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Kurator
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kurator_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
